#!/bin/bash

if [[ $EUID -ne 0 ]]; then
  echo "This script must be run as root"
  exit 1
fi

scriptdir=`dirname $(readlink -f $0)`
NAME=$(cat $scriptdir/../name)
source $scriptdir/../secrets/$NAME
DATE=$(date "+%Y%m%d%H%M%S")

umask 177

tar --ignore-failed-read --one-file-system -cpj --exclude=$BACKUP_DESTINATION / | \
gpg --batch --compress-algo none -e -r $GPGKEY -o $BACKUP_DESTINATION/$NAME.root.$DATE.tar.bz2.gpg
