#!/usr/bin/env bash

if [[ $EUID -ne 0 ]]; then
  echo "This script must be run as root"
  exit 1
fi

scriptdir=`dirname $(readlink -f $0)`
NAME=$(cat $scriptdir/../name)
source $scriptdir/../secrets/$NAME
DATE=$(date --utc "+%Y%m%d%H%M%S")

umask 177

FILES="boot etc home opt root usr/local var/backups var/crash var/local var/mail var/opt var/spool \
var/lib/integrit/known.cdb var/lib/integrit/current.cdb var/log/btmp var/log/wtmp"

tar -C / -cpj --exclude='*/src/*' --exclude='*/backup/*' $FILES | \
gpg --batch --compress-algo none -e -r $GPGKEY -o $BACKUP_DESTINATION/$NAME.config.$DATE.tar.bz2.gpg
