#!/bin/bash

if [[ $EUID -ne 0 ]]; then
  echo "This script must be run as root"
  exit 1
fi

# define ENV variables
DATE=$(date "+%Y%m%d%H%M%S")
HOST=$(hostname --fqdn)
DESTINATION="/mnt/backup"
GPGKEY="22707ACC"

umask 0377

tar -cpj /var/backups | gpg --batch --compress-algo none -e -r $GPGKEY -o $DESTINATION/$HOST.backups.$DATE.tar.bz2.gpg
