#!/bin/bash

if [[ $EUID -ne 0 ]]; then
  echo "This script must be run as root"
  exit 1
fi

# define ENV variables
DATE=$(date "+%Y%m%d%H%M%S")
HOST=$(hostname --fqdn)
DESTINATION="/mnt/backup"
GPGKEY="22707ACC"

umask 177

tar -cpj --exclude='/var/log/journal' /var/log | gpg --batch --compress-algo none -e -r $GPGKEY -o $DESTINATION/$HOST.logs.$DATE.tar.bz2.gpg
