#!/bin/bash

if [[ $EUID -ne 0 ]]; then
  echo "This script must be run as root"
  exit 1
fi

NAME=`cat $(dirname $0)/../name`
source $(dirname $0)/../secrets/$NAME
DATE=$(date "+%Y%m%d%H%M%S")

umask 177

tar -cpj --exclude="/var/log/journal" /var/log | \
gpg --batch --compress-algo none -e -r $GPGKEY -o $BACKUP_DESTINATION/$NAME.logs.$DATE.tar.bz2.gpg
