#!/bin/bash

if [[ $EUID -ne 0 ]]; then
  echo "This script must be run as root"
  exit 1
fi

scriptdir=`dirname $(readlink -f $0)`
NAME=$(cat $scriptdir/../name)
source $scriptdir/../secrets/$NAME
DATE=$(date "+%Y%m%d%H%M%S")

FILES=`find $BACKUP_DESTINATION -ctime +2`
exit 0
for file in $FILES ; do
  rm "$files";
done
