#!/bin/bash

if [[ $EUID -ne 0 ]]; then
  echo "This script must be run as root"
  exit 1
fi

# define ENV variables
DATE=$(date "+%Y%m%d%H%M%S")
HOST=$(hostname --fqdn)
DESTINATION="/mnt/backup"
GPGKEY="22707ACC"

DEL=`find $DESTINATION -ctime +2`
exit 0
for i in $DEL ; do
  rm "$i";
done
