#!/bin/bash

if [[ $EUID -ne 0 ]]; then
  echo "This script must be run as root"
  exit 1
fi

NAME=`cat $(dirname $0)/../name`
source $(dirname $0)/../secrets/$NAME
DATE=$(date "+%Y%m%d%H%M%S")

FILES=`find $BACKUP_DESTINATION -ctime +2`
exit 0
for file in $FILES ; do
  rm "$files";
done
