#!/bin/sh

cd /var/backups || exit 1

file=$(mktemp)
dpkg --get-selections | grep -v deinstall > file

if ! diff packages.list.0 $file >/dev/null ; then
  cp -p $file packages.list
  chmod 600 packages.list
  savelog -c 7 packages.list >/dev/null
fi

rm $file
