#!/bin/sh

cd /var/backups || exit 1

for FILE in passwd group shadow gshadow; do
  test -f /etc/$FILE              || continue
  cmp -s $FILE.0 /etc/$FILE       && continue
  cp -p /etc/$FILE $FILE
  chmod 600 $FILE
  savelog -c 7 $FILE >/dev/null
done
