#! /bin/bash

NAME=`cat $(dirname $0)/../name`
source $(dirname $0)/../secrets/$NAME

RESTIC="restic --cacert $RESTIC_CERT_PATH"
REPO="-r rest:https://$RESTIC_HTTP_USER:$RESTIC_HTTP_PASS@$RESTIC_SERVER:8000/$RESTIC_HTTP_USER/"

$RESTIC $RESTIC_QUIET $REPO backup --one-file-system $RESTIC_BACKUP_PATH
