#!/bin/bash

if [[ $EUID -ne 0 ]]; then
  echo "This script must be run as root"
  exit 1
fi

FILESYSTEMS=( tank/admin tank/data/photo tank/data/radio tank/homes/charlie tank/homes/ian tank/homes/claire tank/homes/freddie tank/projects )

for FILESYSTEM in "${FILESYSTEMS[@]}"
do
  PREV_SNAP=$(zfs list -t snapshot | grep $FILESYSTEM"@offsite" | tail -n 1 | cut -d " " -f1)
  THIS_SNAP=$FILESYSTEM"@offsite-"$(date "+%Y%m%d%H%M%S")
  zfs snapshot $THIS_SNAP
  zfs send -pv -i $PREV_SNAP $THIS_SNAP | zfs recv -duvF offsite-backup
done
