#!/bin/bash

scriptdir=`dirname $(readlink -f $0)`
NAME=$(cat $scriptdir/../name)
source $scriptdir/../secrets/$NAME
DATE=$(date "+%Y%m%d%H%M%S")

umask 177

for DBNAME in "${SQL_DATABASES[@]}"
do
  # assume table format is InnoDB so we can backup in a single transaction without blocking tabel space
  mysqldump --defaults-file=$SQL_DEFAULTS --single-transaction --skip-lock-tables $DBNAME | \
  bzip2 | gpg --batch --compress-algo none -e -r $GPGKEY -o $BACKUP_DESTINATION/$NAME.$DBNAME.$DATE.sql.bz2.gpg
done
