#!/bin/bash

if [[ $EUID -ne 0 ]]; then
  echo "This script must be run as root"
  exit 1
fi

NAME=`cat $(dirname $0)/../name`
source $(dirname $0)/../secrets/$NAME

/usr/bin/env ruby $(dirname $0)/luks-helper.rb open
/usr/bin/env ruby $(dirname $0)/mounter.rb mount
/usr/bin/env ruby $(dirname $0)/zpool-helper.rb import
