#!/bin/bash

if [[ $EUID -ne 0 ]]; then
  echo "This script must be run as root"
  exit 1
fi

scriptdir=`dirname $(readlink -f $0)`
NAME=$(cat $scriptdir/../name)
source $scriptdir/../secrets/$NAME

iscsiadm -m node -L
/usr/bin/env ruby $scriptdir/luks-helper.rb open
/usr/bin/env ruby $scriptdir/mounter.rb mount
/usr/bin/env ruby $scriptdir/zpool-helper.rb import
