#!/usr/bin/env bash

if [[ $EUID -ne 0 ]]; then
  echo "This script must be run as root"
  exit 1
fi

scriptdir=`dirname $(readlink -f $0)`
NAME=$(cat $scriptdir/../name)
source $scriptdir/../secrets/$NAME

/usr/bin/env ruby $scriptdir/zpool-helper.rb export
/usr/bin/env ruby $scriptdir/mounter.rb umount
/usr/bin/env ruby $scriptdir/luks-helper.rb close
umount -a -t nfs
iscsiadm -m node -u
