#!/bin/bash

NAME=`cat $(dirname $0)/../name`
source $(dirname $0)/../secrets/$NAME
DATE=$(date "+%Y%m%d%H%M%S")

umask 177

for WIKI_ROOT in "${WIKI_ROOTS[@]}"
do
  php $WIKI_ROOT/maintenance/dumpBackup.php --full --include-files --logs --uploads | \
  bzip2 | gpg -e -r $GPGKEY -o $BACKUP_DESTINATION/$NAME.$WIKI_NAME.$DATE.xml.bz2.gpg
done
