#!/bin/bash

if [[ $EUID -ne 0 ]]; then
  echo "This script must be run as root"
  exit 1
fi

echo "Opening encrypted vaults..."
cryptsetup luksOpen /dev/disk/by-uuid/6f4c89a2-bf3d-46b0-9648-859beb387f08 offsite-vault1
cryptsetup luksOpen /dev/disk/by-uuid/c3c732c9-95f4-4261-86f7-1950e32a6611 offsite-vault2

echo "Importing ZFS mount..."
zpool import offsite-backup

echo "Done!"
