#!/bin/bash

if [[ $EUID -ne 0 ]]; then
  echo "This script must be run as root"
  exit 1
fi

echo "Opening encrypted vaults..."
cryptsetup luksOpen /dev/disk/by-uuid/52387494-54c6-4e71-98c9-1e7ca1375f69 mirror-vault

echo "Mounting filesystem..."
mount /dev/mapper/mirror-vault /mnt/mirror

echo "Done!"
