#!/bin/bash

if [[ $EUID -ne 0 ]]; then
  echo "This script must be run as root"
  exit 1
fi

echo "Unmounting filesystem..."
umount /dev/mapper/mirror-vault /mnt/mirror

echo "Resealing encrypted vaults..."
cryptsetup luksClose /dev/mapper/mirror-vault

echo "Done!"
