#!/bin/bash

if [[ $EUID -ne 0 ]]; then
  echo "This script must be run as root"
  exit 1
fi

echo "Exporting ZFS mount..."
zpool export offsite-backup

echo "Resealing encrypted vaults..."
cryptsetup luksClose /dev/mapper/offsite-vault1
cryptsetup luksClose /dev/mapper/offsite-vault2

echo "Done!"
