#!/bin/bash

scriptdir=`dirname $(readlink -f $0)`
NAME=$(cat $scriptdir/../name)
source $scriptdir/../secrets/$NAME

RESTIC="restic --cacert $RESTIC_CERT_PATH"
export RESTIC_REPOSITORY="rest:https://$RESTIC_HTTP_USER:$RESTIC_HTTP_PASS@$RESTIC_SERVER:8000/$RESTIC_HTTP_USER/"
EXCLUDE_FILE="$scriptdir/$NAME.excludes"

$RESTIC backup $RESTIC_QUIET --exclude-file=$EXCLUDE_FILE --hostname $NAME $RESTIC_BACKUP_PATH
