#!/bin/bash

scriptdir=`dirname $(readlink -f $0)`
NAME=$(cat $scriptdir/../name)
source $scriptdir/../secrets/$NAME

RESTIC="restic --cacert $RESTIC_CERT_PATH"
REPO="-r rest:https://$RESTIC_HTTP_USER:$RESTIC_HTTP_PASS@$RESTIC_SERVER:8000/$RESTIC_HTTP_USER/"

$RESTIC $RESTIC_QUIET $REPO backup --one-file-system --hostname $NAME $RESTIC_BACKUP_PATH
