#!/usr/bin/env bash

scriptdir=`dirname $(readlink -f $0)`
NAME=$(cat $scriptdir/../name)
source $scriptdir/../secrets/$NAME

export RESTIC_REPOSITORY="rest:https://$RESTIC_HTTP_USER:$RESTIC_HTTP_PASS@$RESTIC_SERVER/$RESTIC_HTTP_USER/"

# Note: this script must be run interactively so we deliberately ignore $RESTIC_QUIET

read -p "Initialise new repository? " -r
if [[ $REPLY =~ ^[Yy]$ ]]
then
  restic init
fi

read -p "Check repository for errors? " -r
if [[ $REPLY =~ ^[Yy]$ ]]
then
  restic check
fi

read -p "Rebuild repository indexes? " -r
if [[ $REPLY =~ ^[Yy]$ ]]
then
  restic rebuild-index
fi

read -p "Prune repository? " -r
if [[ $REPLY =~ ^[Yy]$ ]]
then
  restic prune
fi

read -p "List snapshots? " -r
if [[ $REPLY =~ ^[Yy]$ ]]
then
  restic snapshots
fi

read -p "Remove all exclusive locks? " -r
if [[ $REPLY =~ ^[Yy]$ ]]
then
  restic unlock --remove-all
fi
