#!/usr/bin/env bash

if [[ $EUID -ne 0 ]]; then
  echo "This script must be run as root"
  exit 1
fi

scriptdir=`dirname $(readlink -f $0)`
NAME=$(cat $scriptdir/../name)
source $scriptdir/../secrets/$NAME

for FILESYSTEM in "${ZFS_FILESYSTEMS[@]}"
do
  SNAP=$(zfs list -t snapshot | grep $FILESYSTEM | tail -n1 | cut -d " " -f1)
  zfs send -cpv $SNAP | ssh $ZFS_MIRROR_HOST zfs recv -du $ZFS_MIRROR
done
