#!/bin/bash

if [[ $EUID -ne 0 ]]; then
  echo "This script must be run as root"
  exit 1
fi

scriptdir=`dirname $(readlink -f $0)`
NAME=$(cat $scriptdir/../name)
source $scriptdir/../secrets/$NAME

for FILESYSTEM in "${ZFS_FILESYSTEMS[@]}"
do
  PREV_SNAP=$(zfs list -t snapshot | grep $FILESYSTEM"@offsite" | tail -n 1 | cut -d " " -f1)
  THIS_SNAP=$FILESYSTEM"@offsite-"$(date "+%Y%m%d%H%M%S")
  zfs snapshot $THIS_SNAP
  zfs send -pv -i $PREV_SNAP $THIS_SNAP | zfs recv -duvF $ZFS_OFFSITE
done
