#!/usr/bin/env bash

if [[ $EUID -ne 0 ]]; then
  echo "This script must be run as root"
  exit 1
fi

[ ! "$@" ] && echo "Usage: $0 /path/to/apt-clone.tar.gz"
apt-clone restore-new-distro $@ $(lsb_release -sc)
