#!/bin/bash

if [[ $EUID -ne 0 ]]; then
  echo "This script must be run as root"
  exit 1
fi

( exec $(dirname $0)/../backup/integrit-backup )

rm /var/lib/integrit/current.cdb /var/lib/integrit/known.cdb
/usr/sbin/integrit -C /etc/integrit/integrit.conf -u
cp -a /var/lib/integrit/current.cdb /var/lib/integrit/known.cdb
