#!/bin/bash

if [[ $EUID -ne 0 ]]; then
  echo "This script must be run as root"
  exit 1
fi

scriptdir=`dirname $(readlink -f $0)`

$scriptdir/../backups/integrit-backup

rm /var/lib/integrit/current.cdb /var/lib/integrit/known.cdb
/usr/sbin/integrit -C /etc/integrit/integrit.conf -u
cp -a /var/lib/integrit/current.cdb /var/lib/integrit/known.cdb
