#!/bin/bash

if [[ $EUID -ne 0 ]]; then
  echo "This script must be run as root"
  exit 1
fi

scriptdir=`dirname $(readlink -f $0)`
NAME=$(cat $scriptdir/../name)
source $scriptdir/../secrets/$NAME
TEMP=$(mktemp -d)

chmod 700 $TEMP && cd $TEMP
umask 177

for UUID in "${LUKS_UUIDS[@]}"
do
  cryptsetup luksHeaderBackup /dev/disk/by-uuid/$UUID --header-backup-file $UUID.luksheader
done

for FILE in luks_header_backup_*.img; do
  gpg --batch -r 22707ACC -o $BACKUP_DESTINATION/$FILE.gpg -e $FILE
  chmod 400 $BACKUP_DESTINATION/$FILE.gpg
done

cd && rm -rf $TEMP
