#!/bin/bash

if [[ $EUID -ne 0 ]]; then
  echo "This script must be run as root"
  exit 1
fi

NAME=`cat $(dirname $0)/../name`
source $(dirname $0)/../secrets/$NAME

certbot renew --force-renewal --rsa-key-size 4096 --email $CERT_EMAIL --agree-tos --noninteractive
