#!/bin/bash

if [[ $EUID -ne 0 ]]; then
  echo "This script must be run as root"
  exit 1
fi

scriptdir=`dirname $(readlink -f $0)`
NAME=$(cat $scriptdir/../name)
source $scriptdir/../secrets/$NAME

for VM_NAME in "${VM_NAMES[@]}"
do
  sudo -u virtualbox VBoxManage controlvm $VM_NAME poweroff
done
